# Hello, world!
#
# This is an example function named 'hello'
# which prints 'Hello, world!'.
#
# You can learn more about package authoring with RStudio at:
#
#   http://r-pkgs.had.co.nz/
#
# Some useful keyboard shortcuts for package authoring:
#
#   Install Package:           'Ctrl + Shift + B'
#   Check Package:             'Ctrl + Shift + E'
#   Test Package:              'Ctrl + Shift + T'
#   ROxgyen2 skeleton:         'Ctrl + Shift + Alt + R'
#   Re-render rmd to md with github actions  usethis::use_github_action("render-rmarkdown")
#   generate the documentation files using      roxygen2::roxygenise()
#   add package dependency      usethis::use_package('dplyr')

#   add package dependency [NAMESPACE file should be generated by roxygen2]

# # Add a dependency
# usethis::use_package('tibble', min_version = TRUE)
# # (Re-)build NAMESPACE
# devtools::document()
# # Reload the package: CTRL-L or
# devtools::load_all()

## increment the version
# usethis::use_dev_version()

## default(recommendend)
# usethis::use_package()
# # exact version
# usethis::use_package("dplyr", min_version = "1.0.0")
# # min version = currently installed version
# usethis::use_package("dplyr", min_version = TRUE)


hello <- function() {
  print("Hello, world!")
}
